### ISSUE TITLE
Not detecting all enabled payment methods

### ISSUE THREAD

**Issue by gaiterjones** [galacticlabs/customer-group-payment-filters#3]
Thanks for this module, after installing the module is not detecting all my enabled payment methods. Do I have to manually configure the methods I want the module to include or should the be automatically detected?

**Comment by taoufiqaitali** [comment]
same issue for me, i use stripe, it not show all stripe payment methods like stripe sepa

**Comment by alanablett** [comment]
> Thanks for this module, after installing the module is not detecting all my enabled payment methods. Do I have to manually configure the methods I want the module to include or should the be automatically detected?

@gaiterjones I'm not sure why your methods would not be picked up. In order to populate the multi-select box in the admin area, I use the core Magento Payment helper to fetch out all payment methods available. You can see that here https://github.com/galacticlabs/customer-group-payment-filters/blob/master/Plugin/Block/Aminhtml/Group/Edit/FormPlugin.php#L87 There is no requirement to set any extra information of the payment methods.

What I would suggest is to dump out the `$paymentOptions` variable in `Plugin/Block/Aminhtml/Group/Edit/FormPlugin.php` line 87 to see what you have. When you navigate to any of the customer groups in the admin you should be able to see a dump of the methods available.

```php
private function getPaymentMethodsList()
{
    $paymentOptions = $this->paymentHelper->getPaymentMethodList();

    var_dump($paymentOptions);
    die();
```

If this is still an issue can you paste the result of that dump so I can see what's going on please. Also, what additional methods are you using that are not showing up in that list? If they are free modules I can install I'll be able to debug more. Thanks.

**Comment by alanablett** [comment]
> same issue for me, i use stripe, it not show all stripe payment methods like stripe sepa

@taoufiqaitali I installed the stripe module from here https://marketplace.magento.com/stripeofficial-stripe-payments.html on a fresh copy of Magento 2.3.0. Are you using a different Stripe module? It seems the methods were added successfully as per my screenshot. It might be worth trying to dump the payment methods out as I have instructed above so we can see what's going on.

![Screenshot 2019-05-24 at 11 49 48](https://user-images.githubusercontent.com/1838355/58322841-13ec1800-7e1a-11e9-9af7-be4e0da73d42.png)

**Comment by alanablett** [comment]
@gaiterjones @taoufiqaitali Feel free to respond if you are still having problems, otherwise I will close this issue.

**Comment by taoufiqaitali** [comment]
Hi 
check attached pictures, it not show all payment methods
i have magento 2.3.1 
stripe  2.0.13
![Screenshot from 2019-06-17 19-18-21](https://user-images.githubusercontent.com/22837086/59627203-91fbc000-9135-11e9-8b48-0a658ee1c1d7.png)
![Screenshot from 2019-06-17 19-20-19](https://user-images.githubusercontent.com/22837086/59627204-91fbc000-9135-11e9-9cc6-c173c2843eb3.png)

**Comment by alanablett** [comment]
Hi @taoufiqaitali 

I assume you are using this module https://packagist.org/packages/stripeofficial/stripe-payments

If so, the latest version is 2.0.12. Can you check the check the returned payment methods as instructed above https://github.com/galacticlabs/customer-group-payment-filters/issues/3#issuecomment-495570895 and let me know what you get.

Are you sure you don't have any other modules restricting the returned payment methods?

I'm keen to get to the bottom of this but as i'm unable to replicate the issue i'm afraid.

**Comment by taoufiqaitali** [comment]
> Hi @taoufiqaitali
> 
> I assume you are using this module https://packagist.org/packages/stripeofficial/stripe-payments
> 
> If so, the latest version is 2.0.12. Can you check the check the returned payment methods as instructed above [#3 (comment)](https://github.com/galacticlabs/customer-group-payment-filters/issues/3#issuecomment-495570895) and let me know what you get.
> 
> Are you sure you don't have any other modules restricting the returned payment methods?
> 
> I'm keen to get to the bottom of this but as i'm unable to replicate the issue i'm afraid.

Hi @alanablett i did dump and it not show method credit card strip
when i did some searches i find that function show active payment methods, dont know why list process creditcard as not active so it not displayed
i changed getPaymentMethodList with getPaymentMethods and i get all payment methods(active and not active) 
i will create pull request about changes i did to make it work
